input {
  file {
    path => "/var/log/notification-platform/notification-platform.json"
    start_position => "beginning"
    sincedb_path => "/tmp/notification-platform-logstash.sincedb"
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "service.name" => "notification-platform"
      "environment" => "${APP_ENV:local}"
    }
  }

  if ![correlationId] and [mdc][correlationId] {
    mutate { add_field => { "correlationId" => "%{[mdc][correlationId]}" } }
  }

  if ![requestId] and [mdc][requestId] {
    mutate { add_field => { "requestId" => "%{[mdc][requestId]}" } }
  }
}

output {
  elasticsearch {
    hosts => [ "http://elasticsearch:9200" ]
    index => "notification-platform-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
